"""empty message

Revision ID: f5734bb2bf7a
Revises: 2fbfd6e1659d
Create Date: 2020-12-19 21:54:04.175856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5734bb2bf7a'
down_revision = '2fbfd6e1659d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
